import "@/css/tailwind-base.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    // TODO MAKE ME
};

// TODO MAKE VIEWPORT OBJECT

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className="antialiased">{children}</body>
        </html>
    );
}
