name: Next.js CD

concurrency:
    group: production
    cancel-in-progress: true

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: self-hosted
        environment: production

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js (22.x)
              uses: actions/setup-node@v4
              with:
                node-version: "22.x"
                cache: "npm"
                cache-dependency-path: "src/package-lock.json"

            - name: Delete Old Folders
              run: rm -rf node_modules/ .next/
              working-directory: src

            - name: Install Dependencies
              run: npm install --legacy-peer-deps
              working-directory: src

            - name: Disable Next.js Telemetry
              run: npx next telemetry disable
              working-directory: src

            - name: Build
              run: npm run build
              working-directory: src
              env:
                GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

            - name: Restart PM2
              run: pm2 restart all
              working-directory: src
